# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'biyos.ui'
#
# Created: Sat Apr 16 11:30:12 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(480, 640)
        self.tum_borclar_buton = QtGui.QPushButton(MainWindow)
        self.tum_borclar_buton.setGeometry(QtCore.QRect(240, 450, 181, 61))
        self.tum_borclar_buton.setObjectName(_fromUtf8("tum_borclar_buton"))
        self.apartman_aidat_buton = QtGui.QPushButton(MainWindow)
        self.apartman_aidat_buton.setGeometry(QtCore.QRect(50, 450, 171, 61))
        self.apartman_aidat_buton.setObjectName(_fromUtf8("apartman_aidat_buton"))
        self.frame = QtGui.QFrame(MainWindow)
        self.frame.setGeometry(QtCore.QRect(50, 520, 371, 111))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 341, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioA = QtGui.QRadioButton(self.groupBox)
        self.radioA.setGeometry(QtCore.QRect(0, 20, 71, 51))
        self.radioA.setObjectName(_fromUtf8("radioA"))
        self.radioB = QtGui.QRadioButton(self.groupBox)
        self.radioB.setGeometry(QtCore.QRect(80, 20, 81, 51))
        self.radioB.setObjectName(_fromUtf8("radioB"))
        self.tekil_borc = QtGui.QPushButton(self.groupBox)
        self.tekil_borc.setGeometry(QtCore.QRect(180, 30, 161, 61))
        self.tekil_borc.setObjectName(_fromUtf8("tekil_borc"))
        self.daire_no = QtGui.QLineEdit(self.groupBox)
        self.daire_no.setGeometry(QtCore.QRect(80, 60, 91, 32))
        self.daire_no.setObjectName(_fromUtf8("daire_no"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 60, 71, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.giris = QtGui.QPushButton(MainWindow)
        self.giris.setGeometry(QtCore.QRect(60, 10, 361, 51))
        self.giris.setObjectName(_fromUtf8("giris"))
        self.groupBox_2 = QtGui.QGroupBox(MainWindow)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 70, 401, 361))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.kalori_hesap_buton = QtGui.QPushButton(self.groupBox_2)
        self.kalori_hesap_buton.setGeometry(QtCore.QRect(200, 120, 181, 51))
        self.kalori_hesap_buton.setObjectName(_fromUtf8("kalori_hesap_buton"))
        self.kalori_veri_buton = QtGui.QPushButton(self.groupBox_2)
        self.kalori_veri_buton.setGeometry(QtCore.QRect(10, 120, 181, 51))
        self.kalori_veri_buton.setObjectName(_fromUtf8("kalori_veri_buton"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 180, 391, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(140, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(270, 20, 111, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.su_toplam_disp = QtGui.QTextEdit(self.groupBox_3)
        self.su_toplam_disp.setGeometry(QtCore.QRect(10, 50, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.su_toplam_disp.setFont(font)
        self.su_toplam_disp.setReadOnly(True)
        self.su_toplam_disp.setAcceptRichText(False)
        self.su_toplam_disp.setObjectName(_fromUtf8("su_toplam_disp"))
        self.kalori_toplam_disp = QtGui.QTextEdit(self.groupBox_3)
        self.kalori_toplam_disp.setGeometry(QtCore.QRect(140, 50, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kalori_toplam_disp.setFont(font)
        self.kalori_toplam_disp.setReadOnly(True)
        self.kalori_toplam_disp.setAcceptRichText(False)
        self.kalori_toplam_disp.setObjectName(_fromUtf8("kalori_toplam_disp"))
        self.kalori_ortalama_disp = QtGui.QTextEdit(self.groupBox_3)
        self.kalori_ortalama_disp.setGeometry(QtCore.QRect(270, 50, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kalori_ortalama_disp.setFont(font)
        self.kalori_ortalama_disp.setReadOnly(True)
        self.kalori_ortalama_disp.setAcceptRichText(False)
        self.kalori_ortalama_disp.setObjectName(_fromUtf8("kalori_ortalama_disp"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 20, 391, 91))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.su_birim_in = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.su_birim_in.setGeometry(QtCore.QRect(130, 40, 81, 41))
        self.su_birim_in.setMaximum(19.99)
        self.su_birim_in.setObjectName(_fromUtf8("su_birim_in"))
        self.dogalgaz_birim_in = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.dogalgaz_birim_in.setGeometry(QtCore.QRect(10, 40, 81, 41))
        self.dogalgaz_birim_in.setMaximum(19.99)
        self.dogalgaz_birim_in.setObjectName(_fromUtf8("dogalgaz_birim_in"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(130, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.fatura_in = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.fatura_in.setGeometry(QtCore.QRect(250, 40, 131, 41))
        self.fatura_in.setMaximum(999999.99)
        self.fatura_in.setObjectName(_fromUtf8("fatura_in"))
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(250, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 290, 161, 51))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.son_fiyat_disp = QtGui.QTextEdit(self.groupBox_2)
        self.son_fiyat_disp.setGeometry(QtCore.QRect(200, 290, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.son_fiyat_disp.setFont(font)
        self.son_fiyat_disp.setReadOnly(True)
        self.son_fiyat_disp.setAcceptRichText(False)
        self.son_fiyat_disp.setObjectName(_fromUtf8("son_fiyat_disp"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Form", None))
        self.tum_borclar_buton.setText(_translate("MainWindow", "Tüm kişisel borçları yazdır", None))
        self.apartman_aidat_buton.setText(_translate("MainWindow", "Aidat borçlarını yazdır", None))
        self.groupBox.setTitle(_translate("MainWindow", "Tek borç yazdır", None))
        self.radioA.setText(_translate("MainWindow", "A blok", None))
        self.radioB.setText(_translate("MainWindow", "B blok", None))
        self.tekil_borc.setText(_translate("MainWindow", "Yazdır", None))
        self.label.setText(_translate("MainWindow", "Daire No:", None))
        self.giris.setText(_translate("MainWindow", "Giriş yap", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Kalorimetre Hesabı", None))
        self.kalori_hesap_buton.setText(_translate("MainWindow", "Hesapla", None))
        self.kalori_veri_buton.setText(_translate("MainWindow", "Verileri göster", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Sayaç verileri", None))
        self.label_2.setText(_translate("MainWindow", "Su sayaç toplam", None))
        self.label_3.setText(_translate("MainWindow", "Kalori toplam", None))
        self.label_4.setText(_translate("MainWindow", "Kalori ortalama", None))
        self.label_6.setText(_translate("MainWindow", "Doğal gaz birim", None))
        self.label_7.setText(_translate("MainWindow", "Su birim fiyat", None))
        self.label_8.setText(_translate("MainWindow", "Fatura", None))
        self.label_5.setText(_translate("MainWindow", "Dağıtılacak Son Fiyat:", None))

