# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'biyos.ui'
#
# Created: Sat Apr 23 22:31:50 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 570)
        self.giris_button = QtGui.QPushButton(MainWindow)
        self.giris_button.setGeometry(QtCore.QRect(60, 10, 531, 51))
        self.giris_button.setObjectName(_fromUtf8("giris_button"))
        self.groupBox_2 = QtGui.QGroupBox(MainWindow)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 70, 401, 291))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.kalori_hesap_button = QtGui.QPushButton(self.groupBox_2)
        self.kalori_hesap_button.setGeometry(QtCore.QRect(10, 120, 371, 51))
        self.kalori_hesap_button.setObjectName(_fromUtf8("kalori_hesap_button"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 20, 391, 91))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.su_birim_in = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.su_birim_in.setGeometry(QtCore.QRect(140, 40, 91, 41))
        self.su_birim_in.setMaximum(19.99)
        self.su_birim_in.setObjectName(_fromUtf8("su_birim_in"))
        self.dogalgaz_birim_in = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.dogalgaz_birim_in.setGeometry(QtCore.QRect(10, 40, 91, 41))
        self.dogalgaz_birim_in.setMaximum(19.99)
        self.dogalgaz_birim_in.setObjectName(_fromUtf8("dogalgaz_birim_in"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(140, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.fatura_in = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.fatura_in.setGeometry(QtCore.QRect(250, 40, 131, 41))
        self.fatura_in.setMaximum(999999.99)
        self.fatura_in.setObjectName(_fromUtf8("fatura_in"))
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(250, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 201, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.son_fiyat_disp = QtGui.QTextEdit(self.groupBox_2)
        self.son_fiyat_disp.setGeometry(QtCore.QRect(220, 190, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.son_fiyat_disp.setFont(font)
        self.son_fiyat_disp.setReadOnly(True)
        self.son_fiyat_disp.setAcceptRichText(False)
        self.son_fiyat_disp.setObjectName(_fromUtf8("son_fiyat_disp"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 260, 101, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(220, 260, 61, 31))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.ortak_gider_disp = QtGui.QTextEdit(self.groupBox_2)
        self.ortak_gider_disp.setGeometry(QtCore.QRect(110, 250, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ortak_gider_disp.setFont(font)
        self.ortak_gider_disp.setReadOnly(True)
        self.ortak_gider_disp.setAcceptRichText(False)
        self.ortak_gider_disp.setObjectName(_fromUtf8("ortak_gider_disp"))
        self.aidat_disp = QtGui.QTextEdit(self.groupBox_2)
        self.aidat_disp.setGeometry(QtCore.QRect(290, 250, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.aidat_disp.setFont(font)
        self.aidat_disp.setReadOnly(True)
        self.aidat_disp.setAcceptRichText(False)
        self.aidat_disp.setObjectName(_fromUtf8("aidat_disp"))
        self.groupBox_3 = QtGui.QGroupBox(MainWindow)
        self.groupBox_3.setGeometry(QtCore.QRect(440, 70, 181, 341))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.su_toplam_disp = QtGui.QTextEdit(self.groupBox_3)
        self.su_toplam_disp.setGeometry(QtCore.QRect(10, 60, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.su_toplam_disp.setFont(font)
        self.su_toplam_disp.setReadOnly(True)
        self.su_toplam_disp.setAcceptRichText(False)
        self.su_toplam_disp.setObjectName(_fromUtf8("su_toplam_disp"))
        self.kalori_ortalama_disp = QtGui.QTextEdit(self.groupBox_3)
        self.kalori_ortalama_disp.setGeometry(QtCore.QRect(10, 220, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kalori_ortalama_disp.setFont(font)
        self.kalori_ortalama_disp.setReadOnly(True)
        self.kalori_ortalama_disp.setAcceptRichText(False)
        self.kalori_ortalama_disp.setObjectName(_fromUtf8("kalori_ortalama_disp"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.kalori_toplam_disp = QtGui.QTextEdit(self.groupBox_3)
        self.kalori_toplam_disp.setGeometry(QtCore.QRect(10, 140, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kalori_toplam_disp.setFont(font)
        self.kalori_toplam_disp.setReadOnly(True)
        self.kalori_toplam_disp.setAcceptRichText(False)
        self.kalori_toplam_disp.setObjectName(_fromUtf8("kalori_toplam_disp"))
        self.sayac_veri_button = QtGui.QPushButton(self.groupBox_3)
        self.sayac_veri_button.setGeometry(QtCore.QRect(10, 280, 151, 51))
        self.sayac_veri_button.setObjectName(_fromUtf8("sayac_veri_button"))
        self.tabWidget = QtGui.QTabWidget(MainWindow)
        self.tabWidget.setGeometry(QtCore.QRect(20, 400, 601, 161))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.apartman_aidat_button = QtGui.QPushButton(self.tab)
        self.apartman_aidat_button.setGeometry(QtCore.QRect(10, 60, 581, 51))
        self.apartman_aidat_button.setObjectName(_fromUtf8("apartman_aidat_button"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 16, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(220, 20, 291, 21))
        self.label_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_12.setMouseTracking(True)
        self.label_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setOpenExternalLinks(True)
        self.label_12.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.paylasim_link_in = QtGui.QDoubleSpinBox(self.tab)
        self.paylasim_link_in.setGeometry(QtCore.QRect(510, 10, 81, 41))
        self.paylasim_link_in.setDecimals(0)
        self.paylasim_link_in.setMaximum(10000.0)
        self.paylasim_link_in.setObjectName(_fromUtf8("paylasim_link_in"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tum_borclar_button = QtGui.QPushButton(self.tab_2)
        self.tum_borclar_button.setGeometry(QtCore.QRect(10, 10, 201, 111))
        self.tum_borclar_button.setObjectName(_fromUtf8("tum_borclar_button"))
        self.frame = QtGui.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(220, 10, 371, 111))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 341, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.a_blok_in = QtGui.QRadioButton(self.groupBox)
        self.a_blok_in.setGeometry(QtCore.QRect(0, 20, 71, 51))
        self.a_blok_in.setObjectName(_fromUtf8("a_blok_in"))
        self.b_blok_in = QtGui.QRadioButton(self.groupBox)
        self.b_blok_in.setGeometry(QtCore.QRect(80, 20, 81, 51))
        self.b_blok_in.setObjectName(_fromUtf8("b_blok_in"))
        self.tek_borc_button = QtGui.QPushButton(self.groupBox)
        self.tek_borc_button.setGeometry(QtCore.QRect(180, 30, 161, 61))
        self.tek_borc_button.setObjectName(_fromUtf8("tek_borc_button"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 60, 71, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.daire_no_in = QtGui.QDoubleSpinBox(self.groupBox)
        self.daire_no_in.setGeometry(QtCore.QRect(80, 60, 71, 31))
        self.daire_no_in.setDecimals(0)
        self.daire_no_in.setMinimum(1.0)
        self.daire_no_in.setMaximum(24.0)
        self.daire_no_in.setObjectName(_fromUtf8("daire_no_in"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Form", None))
        self.giris_button.setText(_translate("MainWindow", "Giriş yap", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Kalorimetre Hesabı", None))
        self.kalori_hesap_button.setText(_translate("MainWindow", "Hesapla", None))
        self.label_6.setText(_translate("MainWindow", "Doğal gaz birim", None))
        self.label_7.setText(_translate("MainWindow", "Su birim fiyat", None))
        self.label_8.setText(_translate("MainWindow", "Fatura", None))
        self.label_5.setText(_translate("MainWindow", "Dağıtılacak doğal gaz (TL)", None))
        self.label_9.setText(_translate("MainWindow", "Ortak gider", None))
        self.label_10.setText(_translate("MainWindow", "Aidat", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Sayaç verileri", None))
        self.label_2.setText(_translate("MainWindow", "Su sayaç toplam", None))
        self.label_4.setText(_translate("MainWindow", "Kalori ortalama", None))
        self.label_11.setText(_translate("MainWindow", "Kalori toplam", None))
        self.sayac_veri_button.setText(_translate("MainWindow", "Verileri göster", None))
        self.apartman_aidat_button.setText(_translate("MainWindow", "Aylık apartman borçlarını yazdır", None))
        self.label_3.setText(_translate("MainWindow", "Borç yazdırılacak ay linki:", None))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://app.biyos.net/raporlar/paylasimlar/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://app.biyos.net/raporlar/paylasimlar/</span></a></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Apartman Borç Tablosu", None))
        self.tum_borclar_button.setText(_translate("MainWindow", "Tüm kişisel borçları yazdır", None))
        self.groupBox.setTitle(_translate("MainWindow", "Tek borç yazdır", None))
        self.a_blok_in.setText(_translate("MainWindow", "A blok", None))
        self.b_blok_in.setText(_translate("MainWindow", "B blok", None))
        self.tek_borc_button.setText(_translate("MainWindow", "Yazdır", None))
        self.label.setText(_translate("MainWindow", "Daire No:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Daire Borç Tablosu", None))

